// <auto-generated />
using System;
using DashBoardDAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DashBoardDAL.Migrations
{
    [DbContext(typeof(DBConnect))]
    partial class DBConnectModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DashBoardDAL.Entities.BoardEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("UserOwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserOwnerId");

                    b.ToTable("Board");
                });

            modelBuilder.Entity("DashBoardDAL.Entities.ContentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BoardId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("TitleBoardId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TitleBoardId");

                    b.ToTable("Content");
                });

            modelBuilder.Entity("DashBoardDAL.Entities.ProjectEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NameProject")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("DashBoardDAL.Entities.TeamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("DashBoardDAL.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(384)
                        .HasColumnType("nvarchar(384)");

                    b.Property<byte[]>("Passwd")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varbinary(512)");

                    b.Property<int?>("ProjectEntityId")
                        .HasColumnType("int");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("SaltKey")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varbinary(16)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectEntityId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("TeamEntityUserEntity", b =>
                {
                    b.Property<int>("TeamUsersId")
                        .HasColumnType("int");

                    b.Property<int>("TeamsId")
                        .HasColumnType("int");

                    b.HasKey("TeamUsersId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("TeamEntityUserEntity");
                });

            modelBuilder.Entity("DashBoardDAL.Entities.BoardEntity", b =>
                {
                    b.HasOne("DashBoardDAL.Entities.UserEntity", "UserOwner")
                        .WithMany("Boards")
                        .HasForeignKey("UserOwnerId");

                    b.Navigation("UserOwner");
                });

            modelBuilder.Entity("DashBoardDAL.Entities.ContentEntity", b =>
                {
                    b.HasOne("DashBoardDAL.Entities.BoardEntity", "TitleBoard")
                        .WithMany("Contents")
                        .HasForeignKey("TitleBoardId");

                    b.Navigation("TitleBoard");
                });

            modelBuilder.Entity("DashBoardDAL.Entities.UserEntity", b =>
                {
                    b.HasOne("DashBoardDAL.Entities.ProjectEntity", null)
                        .WithMany("TeamsUsers")
                        .HasForeignKey("ProjectEntityId");
                });

            modelBuilder.Entity("TeamEntityUserEntity", b =>
                {
                    b.HasOne("DashBoardDAL.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("TeamUsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DashBoardDAL.Entities.TeamEntity", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DashBoardDAL.Entities.BoardEntity", b =>
                {
                    b.Navigation("Contents");
                });

            modelBuilder.Entity("DashBoardDAL.Entities.ProjectEntity", b =>
                {
                    b.Navigation("TeamsUsers");
                });

            modelBuilder.Entity("DashBoardDAL.Entities.UserEntity", b =>
                {
                    b.Navigation("Boards");
                });
#pragma warning restore 612, 618
        }
    }
}
